#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command Line Client for Vagrancy.

Copyright (c) 2020 by Clemens Rabe <clemens.rabe@clemensrabe.de>
All rights reserved.
This file is part of vagrancyCtrl (https://github.com/seeraven/vagrancyCtrl) and
is released under the "BSD 3-Clause License". Please see the LICENSE file that
is included as part of this package.
"""


# -----------------------------------------------------------------------------
# Module Import
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# EOF
# -----------------------------------------------------------------------------
